[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
fav_me = "FhnC7vwL3VV6n5kZn85GmRo1k5NeXLLRaHkUYzMh9eXJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/apple/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
